[build-system]
requires = [ "poetry>=0.12",]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "gameta"
version = "0.1.2"
description = "Genisys tool for handling meta-repositories"
license = "MIT"
authors = [ "David Lee <ltw_david@hotmail.com>",]
exclude = [ "tests", ]
packages = [
    {include = "gameta"},
]

[tool.tox]
legacy_tox_ini = """
[tox]
isolated_build = True
envlist = py37,py38

[testenv]
commands = python -m unittest discover -v -s ./tests -t .
"""

[tool.poetry.dependencies]
python = ">=3.7"
Click = "^7.1.2"
colorama = "^0.4.3"
gitpython = "^3.1.9"

[tool.poetry.dev-dependencies]
mkdocs = "^1.1.2"
tox = "^3.16.1"
tox-pyenv = "^1.1.0"

[tool.poetry.scripts]
gameta = "gameta.cli:gameta_cli"