version: 2.1

orbs:
  python: circleci/python@1.2.0

jobs:
  test:
    docker:
      - image: "fkrull/multi-python:bionic"
    steps:
      - checkout
      - run:
          name: Test
          command: tox
  docs:
    docker:
      - image: "fkrull/multi-python:bionic"
    steps:
      - checkout
      - run:
          name: Setting up Virtual Environment
          command: python3.7 -m venv venv && source venv/bin/activate
      - run:
          name: Install dependencies
          command: pip install -U pip mkdocs
      - run:
          name: Test
          command: echo $PYPI_USER
      - run:
          name: Build documentation
          command: cd docs && mkdocs gh-deploy
  deploy:
    docker:
      - image: "fkrull/multi-python:bionic"
    steps:
      - checkout
      - run:
          name: Setting up Virtual Environment
          command: python3.7 -m venv venv && source venv/bin/activate
      - run:
          name: Install dependencies
          command: pip3 install -U pip poetry
      - run:
          name: Publish
          command: echo $PYPI_USER
#          command: poetry publish --build -u $PYPI_USER -p $PYPI_PASSWORD

workflows:
  main:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - gh-pages
            tags:
              only: /^*.*.*/
      - docs:
          context:
            - "Genisys Context"
          requires:
            - test
#          filters: &deploy-config
#            branches:
#              ignore: /.*/
#            tags:
#              only: /^*.*.*/
#      - deploy:
#          context:
#            - "Genisys Context"
#          requires:
#            - docs
#          filters:
#            <<: *deploy-config
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - test
